spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    active: home
server:
  port: 8080
  context-path: /yzone

xiumeiApiUrl: http://zzz.mt27z.cn/ab/bd